import Head from "next/head";
import HomeX from "@/componets/HomeX";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <HomeX />
      </main>
    </>
  );
}
